import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/component/Footer";
import Header from "@/component/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className="!scroll-smooth relative  ">
      <body  className={`${inter.className} pl-5 pr-5   bg-gray-50 text-gray-950  relative pt-28 sm:pt-36 dark:bg-[#0a192f] dark:text-gray-50 dark:text-opacity-90 `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
